### ISSUE TITLE
DropDown unter Textfeldern

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/yform_flexible_content#10]
Die Auswahl der Gruppen (dropdown-menu) ist hinter den Textfeldern (CkEditor) 

![image](https://github.com/FriendsOfREDAXO/yform_flexible_content/assets/330516/324c2b28-22f6-463c-a840-7a3f73261392)

**Comment by eaCe** [comment]
Der doofe CK macht alles kaputt :D
